%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-autoware-lanelet2-extension
Version:        0.4.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS autoware_lanelet2_extension package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       GeographicLib-devel
Requires:       pugixml-devel
Requires:       range-v3-devel
Requires:       ros-jazzy-autoware-map-msgs
Requires:       ros-jazzy-autoware-planning-msgs
Requires:       ros-jazzy-autoware-utils
Requires:       ros-jazzy-geometry-msgs
Requires:       ros-jazzy-lanelet2-core
Requires:       ros-jazzy-lanelet2-io
Requires:       ros-jazzy-lanelet2-maps
Requires:       ros-jazzy-lanelet2-projection
Requires:       ros-jazzy-lanelet2-routing
Requires:       ros-jazzy-lanelet2-traffic-rules
Requires:       ros-jazzy-lanelet2-validation
Requires:       ros-jazzy-rclcpp
Requires:       ros-jazzy-tf2
Requires:       ros-jazzy-tf2-geometry-msgs
Requires:       ros-jazzy-visualization-msgs
Requires:       ros-jazzy-ros-workspace
BuildRequires:  GeographicLib-devel
BuildRequires:  pugixml-devel
BuildRequires:  range-v3-devel
BuildRequires:  ros-jazzy-ament-cmake-auto
BuildRequires:  ros-jazzy-autoware-cmake
BuildRequires:  ros-jazzy-autoware-map-msgs
BuildRequires:  ros-jazzy-autoware-planning-msgs
BuildRequires:  ros-jazzy-autoware-utils
BuildRequires:  ros-jazzy-geometry-msgs
BuildRequires:  ros-jazzy-lanelet2-core
BuildRequires:  ros-jazzy-lanelet2-io
BuildRequires:  ros-jazzy-lanelet2-maps
BuildRequires:  ros-jazzy-lanelet2-projection
BuildRequires:  ros-jazzy-lanelet2-routing
BuildRequires:  ros-jazzy-lanelet2-traffic-rules
BuildRequires:  ros-jazzy-lanelet2-validation
BuildRequires:  ros-jazzy-rclcpp
BuildRequires:  ros-jazzy-tf2
BuildRequires:  ros-jazzy-tf2-geometry-msgs
BuildRequires:  ros-jazzy-visualization-msgs
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-jazzy-ament-cmake-ros
%endif

%description
The autoware_lanelet2_extension package contains libraries to handle Lanelet2
format data.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Mon Jun 24 2024 mitsudome-r <ryohsuke.mitsudome@tier4.jp> - 0.4.0-1
- Autogenerated by Bloom

