%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-autoware-lanelet2-extension-python
Version:        0.7.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS autoware_lanelet2_extension_python package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-python3-devel
Requires:       ros-rolling-autoware-lanelet2-extension
Requires:       ros-rolling-geometry-msgs
Requires:       ros-rolling-lanelet2-core
Requires:       ros-rolling-lanelet2-io
Requires:       ros-rolling-lanelet2-projection
Requires:       ros-rolling-lanelet2-python
Requires:       ros-rolling-lanelet2-routing
Requires:       ros-rolling-lanelet2-traffic-rules
Requires:       ros-rolling-lanelet2-validation
Requires:       ros-rolling-rclcpp
Requires:       ros-rolling-ros-workspace
BuildRequires:  boost-python3-devel
BuildRequires:  ros-rolling-ament-cmake-auto
BuildRequires:  ros-rolling-autoware-cmake
BuildRequires:  ros-rolling-autoware-lanelet2-extension
BuildRequires:  ros-rolling-geometry-msgs
BuildRequires:  ros-rolling-lanelet2-core
BuildRequires:  ros-rolling-lanelet2-io
BuildRequires:  ros-rolling-lanelet2-projection
BuildRequires:  ros-rolling-lanelet2-python
BuildRequires:  ros-rolling-lanelet2-routing
BuildRequires:  ros-rolling-lanelet2-traffic-rules
BuildRequires:  ros-rolling-lanelet2-validation
BuildRequires:  ros-rolling-python-cmake-module
BuildRequires:  ros-rolling-rclcpp
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-rolling-ament-cmake-ros
%endif

%description
The autoware_lanelet2_extension_python package contains Python bindings for
lanelet2_extension package

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/rolling" \
    -DAMENT_PREFIX_PATH="/opt/ros/rolling" \
    -DCMAKE_PREFIX_PATH="/opt/ros/rolling" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Wed May 14 2025 Mamoru Sobue <mamoru.sobue@tier4.jp> - 0.7.2-1
- Autogenerated by Bloom

* Fri Apr 25 2025 Mamoru Sobue <mamoru.sobue@tier4.jp> - 0.7.1-1
- Autogenerated by Bloom

* Mon Apr 07 2025 Mamoru Sobue <mamoru.sobue@tier4.jp> - 0.7.0-1
- Autogenerated by Bloom

* Thu Nov 21 2024 Mamoru Sobue <mamoru.sobue@tier4.jp> - 0.6.2-1
- Autogenerated by Bloom

* Thu Sep 05 2024 Mamoru Sobue <mamoru.sobue@tier4.jp> - 0.6.0-1
- Autogenerated by Bloom

* Wed Jul 10 2024 Mamoru Sobue <mamoru.sobue@tier4.jp> - 0.5.0-1
- Autogenerated by Bloom

* Mon Jun 24 2024 Mamoru Sobue <mamoru.sobue@tier4.jp> - 0.4.0-1
- Autogenerated by Bloom

